import rsf.doc

sfplsurf = rsf.doc.rsfprog('sfplsurf','plot/plplot/plsurf.c','''Generate a surface plot. ''')
sfplsurf.par('wantaxis',rsf.doc.rsfpar('bool','y','','''if generate axes with ticks and labels '''))
sfplsurf.par('wantaxis1',rsf.doc.rsfpar('bool','y','',''''''))
sfplsurf.par('wantaxis2',rsf.doc.rsfpar('bool','y','',''''''))
sfplsurf.par('wantaxis3',rsf.doc.rsfpar('bool','y','',''''''))
sfplsurf.par('wanttitle',rsf.doc.rsfpar('bool','y','','''if include title '''))
sfplsurf.par('labelsz',rsf.doc.rsfpar('float','8.0','','''label font size '''))
sfplsurf.par('titlesz',rsf.doc.rsfpar('float','10.0','','''title font size '''))
sfplsurf.par('labelfat',rsf.doc.rsfpar('int','1','','''label fatness '''))
sfplsurf.par('titlefat',rsf.doc.rsfpar('int','1','','''title fatness '''))
sfplsurf.par('font',rsf.doc.rsfpar('int','2','','''font '''))
sfplsurf.par('minval',rsf.doc.rsfpar('float','SF_HUGE','','''minimum value for the vertical axis (default is data minimum) '''))
sfplsurf.par('maxval',rsf.doc.rsfpar('float','-SF_HUGE','','''maximum value for the vertical axis (default is data maximum) '''))
sfplsurf.par('alt',rsf.doc.rsfpar('float','35.0','','''altitude [0;90] '''))
sfplsurf.par('az',rsf.doc.rsfpar('float','25.0','','''azimuth '''))
sfplsurf.par('mesh',rsf.doc.rsfpar('bool','y','','''what to draw: true - mesh, false - shaded surface '''))
sfplsurf.par('meshc',rsf.doc.rsfpar('int','VP_YELLOW','','''mesh color or surface contour color '''))
sfplsurf.par('sides',rsf.doc.rsfpar('bool','n','','''draw sides '''))
sfplsurf.par('bcontour',rsf.doc.rsfpar('bool','n','','''draw contour lines at the bottom '''))
sfplsurf.par('scontour',rsf.doc.rsfpar('bool','n','','''draw contour lines on the surface (surface mode only) '''))
sfplsurf.par('nc',rsf.doc.rsfpar('int','10','','''number of contour lines '''))
sfplsurf.par('faceted',rsf.doc.rsfpar('bool','n','','''each cell is faceted on the surface (surface mode only) '''))
sfplsurf.par('label1',rsf.doc.rsfpar('string ',desc=''''''))
sfplsurf.par('label2',rsf.doc.rsfpar('string ',desc=''''''))
sfplsurf.par('label3',rsf.doc.rsfpar('string ',desc=''''''))
sfplsurf.par('unit1',rsf.doc.rsfpar('string ',desc=''''''))
sfplsurf.par('unit2',rsf.doc.rsfpar('string ',desc=''''''))
sfplsurf.par('unit3',rsf.doc.rsfpar('string ',desc=''''''))
sfplsurf.par('title',rsf.doc.rsfpar('string ',desc=''''''))
sfplsurf.par('wheretitle',rsf.doc.rsfpar('string ',desc='''where to put title (top,bottom) '''))
sfplsurf.par('color',rsf.doc.rsfpar('string ',desc='''color scheme (default is i) '''))
sfplsurf.version('2.1-git')
sfplsurf.synopsis('''sfplsurf < in.rsf wantaxis=y wantaxis1=y wantaxis2=y wantaxis3=y wanttitle=y labelsz=8.0 titlesz=10.0 labelfat=1 titlefat=1 font=2 minval=SF_HUGE maxval=-SF_HUGE alt=35.0 az=25.0 mesh=y meshc=VP_YELLOW sides=n bcontour=n scontour=n nc=10 faceted=n label1= label2= label3= unit1= unit2= unit3= title= wheretitle= color=''','''''')
rsf.doc.progs['sfplsurf']=sfplsurf

