import rsf.doc

sfbeamform = rsf.doc.rsfprog('sfbeamform','user/pwd/Mbeamform.c','''2-D beam forming. ''')
sfbeamform.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfbeamform.par('rect',rsf.doc.rsfpar('int','3','','''smoothing radius '''))
sfbeamform.par('adj',rsf.doc.rsfpar('bool','y','','''adjoint flag '''))
sfbeamform.par('gauss',rsf.doc.rsfpar('bool','n','','''use pseudo-gaussian '''))
sfbeamform.par('order',rsf.doc.rsfpar('int','1','','''PWD accuracy order '''))
sfbeamform.version('2.1-git')
sfbeamform.synopsis('''sfbeamform < in.rsf dip=dip.rsf > out.rsf rect=3 adj=y gauss=n order=1''','''''')
rsf.doc.progs['sfbeamform']=sfbeamform

sfdealias = rsf.doc.rsfprog('sfdealias','user/pwd/Mdealias.c','''3-D trace interpolation to a denser grid using PWD.''')
sfdealias.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfdealias.par('both',rsf.doc.rsfpar('bool','n','','''if use left and right slopes '''))
sfdealias.par('eps',rsf.doc.rsfpar('float','0.01','','''regularization '''))
sfdealias.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfdealias.version('2.1-git Mdealias2.c 1713 2006-03-03 08:21:29Z fomels')
sfdealias.synopsis('''sfdealias < in.rsf > out.rsf dip=dip.rsf both=n eps=0.01 order=1''','''
It may be necessary to bandpass the data before and after dealiasing 
to ensure that the temporal spectrum is banded. Rule of thumb: if 
max(jx,jy)=N, the temporal bandwidth should be 1/N of Nyquist.
''')
rsf.doc.progs['sfdealias']=sfdealias

sfdealias2 = rsf.doc.rsfprog('sfdealias2','user/pwd/Mdealias2.c','''2-D (inline) trace interpolation to a denser grid using PWD.''')
sfdealias2.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfdealias2.par('both',rsf.doc.rsfpar('bool','n','','''if use left and right slopes '''))
sfdealias2.par('eps',rsf.doc.rsfpar('float','0.01','','''regularization '''))
sfdealias2.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfdealias2.version('2.1-git Mdealias2.c 1713 2006-03-03 08:21:29Z fomels')
sfdealias2.synopsis('''sfdealias2 < in.rsf > out.rsf dip=dip.rsf both=n eps=0.01 order=1''','''
It may be necessary to bandpass the data before and after dealiasing 
to ensure that the temporal spectrum is banded. Rule of thumb: if 
max(jx,jy)=N, the temporal bandwidth should be 1/N of Nyquist.
''')
rsf.doc.progs['sfdealias2']=sfdealias2

sfdijkstra = rsf.doc.rsfprog('sfdijkstra','user/pwd/Mdijkstra.c','''Dijkstra shortest-path algorithm in 2-D ''')
sfdijkstra.par('fin1',rsf.doc.rsfpar('ints','','',''' [nf]'''))
sfdijkstra.par('fin2',rsf.doc.rsfpar('ints','','','''final points  [nf]'''))
sfdijkstra.par('paths',rsf.doc.rsfpar('strings','','',''' [nf]'''))
sfdijkstra.par('ref1',rsf.doc.rsfpar('int','0','',''''''))
sfdijkstra.par('ref2',rsf.doc.rsfpar('int','0','','''source point '''))
sfdijkstra.par('nf',rsf.doc.rsfpar('int','0','','''number of final points '''))
sfdijkstra.version('2.1-git')
sfdijkstra.synopsis('''sfdijkstra < cost.rsf > out.rsf fin1= fin2= paths= ref1=0 ref2=0 nf=0''','''''')
rsf.doc.progs['sfdijkstra']=sfdijkstra

sfdip = rsf.doc.rsfprog('sfdip','user/pwd/Mdip.c','''3-D dip estimation by plane wave destruction. ''')
sfdip.par('mask',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfdip.par('idip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfdip.par('xdip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfdip.par('both',rsf.doc.rsfpar('bool','n','','''if y, compute both left and right predictions '''))
sfdip.par('n4',rsf.doc.rsfpar('int','2','','''what to compute in 3-D. 0: in-line, 1: cross-line, 2: both '''))
sfdip.par('niter',rsf.doc.rsfpar('int','5','','''number of iterations '''))
sfdip.par('liter',rsf.doc.rsfpar('int','20','','''number of linear iterations '''))
sfdip.par('rect1',rsf.doc.rsfpar('int','1','','''dip smoothness on 1st axis '''))
sfdip.par('rect2',rsf.doc.rsfpar('int','1','','''dip smoothness on 2nd axis '''))
sfdip.par('rect3',rsf.doc.rsfpar('int','1','','''dip smoothness on 3rd axuis '''))
sfdip.par('p0',rsf.doc.rsfpar('float','0.','','''initial in-line dip '''))
sfdip.par('q0',rsf.doc.rsfpar('float','0.','','''initial cross-line dip '''))
sfdip.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfdip.par('nj1',rsf.doc.rsfpar('int','1','','''in-line antialiasing '''))
sfdip.par('nj2',rsf.doc.rsfpar('int','1','','''cross-line antialiasing '''))
sfdip.par('verb',rsf.doc.rsfpar('bool','n','','''verbosity flag '''))
sfdip.par('pmin',rsf.doc.rsfpar('float','-FLT_MAX','','''minimum inline dip '''))
sfdip.par('pmax',rsf.doc.rsfpar('float','+FLT_MAX','','''maximum inline dip '''))
sfdip.par('qmin',rsf.doc.rsfpar('float','-FLT_MAX','','''minimum cross-line dip '''))
sfdip.par('qmax',rsf.doc.rsfpar('float','+FLT_MAX','','''maximum cross-line dip '''))
sfdip.par('eps',rsf.doc.rsfpar('float','0.0f','','''regularization '''))
sfdip.par('mask',rsf.doc.rsfpar('string ',desc='''auxiliary input file name'''))
sfdip.par('idip',rsf.doc.rsfpar('string ',desc='''initial in-line dip (auxiliary input file name)'''))
sfdip.par('xdip',rsf.doc.rsfpar('string ',desc='''initial cross-line dip (auxiliary input file name)'''))
sfdip.version('2.1-git')
sfdip.synopsis('''sfdip < in.rsf > out.rsf mask=mask.rsf idip=idip0.rsf xdip=xdip0.rsf both=n n4=2 niter=5 liter=20 rect1=1 rect2=1 rect3=1 p0=0. q0=0. order=1 nj1=1 nj2=1 verb=n pmin=-FLT_MAX pmax=+FLT_MAX qmin=-FLT_MAX qmax=+FLT_MAX eps=0.0f''','''
The output is dimensionless (stepout in time measured in time samples). 

June 2012 program of the month:
http://ahay.org/blog/2012/06/02/program-of-the-month-sfdip/
''')
rsf.doc.progs['sfdip']=sfdip

sfdip2 = rsf.doc.rsfprog('sfdip2','user/pwd/Mdip2.c','''2-D dip estimation by plane wave destruction. ''')
sfdip2.par('mask',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfdip2.par('idip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfdip2.par('niter',rsf.doc.rsfpar('int','5','','''number of iterations '''))
sfdip2.par('liter',rsf.doc.rsfpar('int','20','','''number of linear iterations '''))
sfdip2.par('rect1',rsf.doc.rsfpar('int','1','','''dip smoothness on 1st axis '''))
sfdip2.par('rect2',rsf.doc.rsfpar('int','1','','''dip smoothness on 2nd axis '''))
sfdip2.par('p0',rsf.doc.rsfpar('float','0.','','''initial dip '''))
sfdip2.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfdip2.par('nj1',rsf.doc.rsfpar('int','1','','''antialiasing '''))
sfdip2.par('verb',rsf.doc.rsfpar('bool','n','','''verbosity flag '''))
sfdip2.par('pmin',rsf.doc.rsfpar('float','-FLT_MAX','','''minimum dip '''))
sfdip2.par('pmax',rsf.doc.rsfpar('float','+FLT_MAX','','''maximum dip '''))
sfdip2.par('eps',rsf.doc.rsfpar('float','0.0f','','''regularization '''))
sfdip2.par('mask',rsf.doc.rsfpar('string ',desc='''auxiliary input file name'''))
sfdip2.par('idip',rsf.doc.rsfpar('string ',desc='''initial in-line dip (auxiliary input file name)'''))
sfdip2.version('2.1-git')
sfdip2.synopsis('''sfdip2 < in.rsf > out.rsf mask=mask.rsf idip=idip0.rsf niter=5 liter=20 rect1=1 rect2=1 p0=0. order=1 nj1=1 verb=n pmin=-FLT_MAX pmax=+FLT_MAX eps=0.0f''','''''')
rsf.doc.progs['sfdip2']=sfdip2

sfdiplet = rsf.doc.rsfprog('sfdiplet','user/pwd/Mdiplet.c','''2-D Seislet frame ''')
sfdiplet.par('dips',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfdiplet.par('mask',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfdiplet.par('inv',rsf.doc.rsfpar('bool','n','','''if y, do inverse transform '''))
sfdiplet.par('eps',rsf.doc.rsfpar('float','0.01','','''regularization '''))
sfdiplet.par('verb',rsf.doc.rsfpar('bool','y','','''verbosity flag '''))
sfdiplet.par('twhole',rsf.doc.rsfpar('bool','y','','''threshold flag, if y, whole model, otherwise, each component '''))
sfdiplet.par('decomp',rsf.doc.rsfpar('bool','n','','''do decomposition '''))
sfdiplet.par('ncycle',rsf.doc.rsfpar('int','0','','''number of iterations '''))
sfdiplet.par('niter',rsf.doc.rsfpar('int','1','','''number of Bregman iterations '''))
sfdiplet.par('perc',rsf.doc.rsfpar('float','50.0','','''percentage for sharpening '''))
sfdiplet.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfdiplet.par('mask',rsf.doc.rsfpar('string ',desc='''(optional) data mask file (auxiliary input file name)'''))
sfdiplet.par('type',rsf.doc.rsfpar('string ',desc='''wavelet type (haar,linear,biorthogonal), default is linear '''))
sfdiplet.version('2.1-git')
sfdiplet.synopsis('''sfdiplet < in.rsf > out.rsf dips=dip.rsf mask=mask.rsf inv=n eps=0.01 verb=y twhole=y decomp=n ncycle=0 niter=1 perc=50.0 order=1 type=''','''''')
rsf.doc.progs['sfdiplet']=sfdiplet

sfdips = rsf.doc.rsfprog('sfdips','user/pwd/Mdips.c','''Estimate a number of constant dips using plane-wave destruction. ''')
sfdips.par('dips',rsf.doc.rsfpar('floats','','','''initial dips  [nd]'''))
sfdips.par('nd',rsf.doc.rsfpar('int','','','''number of dips '''))
sfdips.par('order',rsf.doc.rsfpar('int','1','[1,2,3]','''accuracy order '''))
sfdips.par('nj',rsf.doc.rsfpar('int','1','','''antialiasing '''))
sfdips.par('verb',rsf.doc.rsfpar('bool','n','','''verbosity flag '''))
sfdips.par('niter',rsf.doc.rsfpar('int','10','','''number of iterations '''))
sfdips.version('2.1-git')
sfdips.synopsis('''sfdips < in.rsf > out.rsf dips= nd= order=1 nj=1 verb=n niter=10''','''''')
rsf.doc.progs['sfdips']=sfdips

sfdixshape = rsf.doc.rsfprog('sfdixshape','user/pwd/Mdixshape.c','''Convert RMS to interval velocity using LS and shaping regularization.''')
sfdixshape.par('weight',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfdixshape.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfdixshape.par('prior',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfdixshape.par('vrmsout',rsf.doc.rsfpar('file   ',desc='''auxiliary output file name'''))
sfdixshape.par('rect1',rsf.doc.rsfpar('int','3','',''''''))
sfdixshape.par('rect2',rsf.doc.rsfpar('int','3','','''smoothing radius '''))
sfdixshape.par('lam',rsf.doc.rsfpar('float','1.','','''operator scaling for inversion '''))
sfdixshape.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfdixshape.par('niter',rsf.doc.rsfpar('int','100','','''maximum number of iterations '''))
sfdixshape.par('prior',rsf.doc.rsfpar('string ',desc='''prior velocity model (auxiliary input file name)'''))
sfdixshape.par('vrmsout',rsf.doc.rsfpar('string ',desc='''optionally, output predicted vrms (auxiliary output file name)'''))
sfdixshape.version('2.1-git Mdix.c 1131 2005-04-20 18:19:10Z fomels')
sfdixshape.synopsis('''sfdixshape < vrms.rsf > vint.rsf weight=weight.rsf dip=dip.rsf prior=prior.rsf vrmsout=vout.rsf rect1=3 rect2=3 lam=1. order=1 niter=100 rect1= rect2= ...''','''rectN defines the size of the smoothing stencil in N-th dimension.
''')
rsf.doc.progs['sfdixshape']=sfdixshape

sfexplanesignoi = rsf.doc.rsfprog('sfexplanesignoi','user/pwd/Mexplanesignoi.c','''Signal and noise separation using both frequency components and dips. ''')
sfexplanesignoi.par('freq',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfexplanesignoi.par('ndip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfexplanesignoi.par('sdip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfexplanesignoi.par('niter',rsf.doc.rsfpar('int','50','','''maximum number of iterations '''))
sfexplanesignoi.par('eps',rsf.doc.rsfpar('float','1.','','''regularization parameter '''))
sfexplanesignoi.par('verb',rsf.doc.rsfpar('bool','n','','''verbosity flag '''))
sfexplanesignoi.par('order',rsf.doc.rsfpar('int','1','[1,2,3]','''accuracy order '''))
sfexplanesignoi.par('nj1',rsf.doc.rsfpar('int','1','','''antialiasing for first dip '''))
sfexplanesignoi.par('nj2',rsf.doc.rsfpar('int','1','','''antialiasing for second dip '''))
sfexplanesignoi.version('2.1-git')
sfexplanesignoi.synopsis('''sfexplanesignoi < in.rsf freq=freq.rsf ndip=ndip.rsf sdip=sdip.rsf > out.rsf niter=50 eps=1. verb=n order=1 nj1=1 nj2=1''','''''')
rsf.doc.progs['sfexplanesignoi']=sfexplanesignoi

sfexpsignoi = rsf.doc.rsfprog('sfexpsignoi','user/pwd/Mexpsignoi.c','''Signal and noise separation using frequency components. ''')
sfexpsignoi.par('freq',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfexpsignoi.par('niter',rsf.doc.rsfpar('int','50','','''maximum number of iterations '''))
sfexpsignoi.par('eps',rsf.doc.rsfpar('float','1.','','''regularization parameter '''))
sfexpsignoi.par('verb',rsf.doc.rsfpar('bool','n','','''verbosity flag '''))
sfexpsignoi.version('2.1-git')
sfexpsignoi.synopsis('''sfexpsignoi < in.rsf freq=freq.rsf > out.rsf niter=50 eps=1. verb=n''','''''')
rsf.doc.progs['sfexpsignoi']=sfexpsignoi

sffdip = rsf.doc.rsfprog('sffdip','user/pwd/Mfdip.c','''3D fast dip estimation by plane wave destruction ''')
sffdip.par('mask',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sffdip.par('n4',rsf.doc.rsfpar('int','2','','''what to compute in 3-D. 0: in-line, 1: cross-line, 2: both '''))
sffdip.par('liter',rsf.doc.rsfpar('int','20','','''number of linear iterations '''))
sffdip.par('rect1',rsf.doc.rsfpar('int','1','','''dip smoothness on 1st axis '''))
sffdip.par('rect2',rsf.doc.rsfpar('int','1','','''dip smoothness on 2nd axis '''))
sffdip.par('rect3',rsf.doc.rsfpar('int','1','','''dip smoothness on 3rd axuis '''))
sffdip.par('verb',rsf.doc.rsfpar('bool','n','','''verbosity flag '''))
sffdip.par('mask',rsf.doc.rsfpar('string ',desc='''auxiliary input file name'''))
sffdip.version('2.1-git')
sffdip.synopsis('''sffdip < in.rsf > out.rsf mask=mask.rsf n4=2 liter=20 rect1=1 rect2=1 rect3=1 verb=n''','''''')
rsf.doc.progs['sffdip']=sffdip

sfmdip = rsf.doc.rsfprog('sfmdip','user/pwd/Mmdip.c','''2-D multiscale dip estimation by plane wave destruction. ''')
sfmdip.par('mask',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfmdip.par('idip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfmdip.par('niter',rsf.doc.rsfpar('int','5','','''number of iterations '''))
sfmdip.par('liter',rsf.doc.rsfpar('int','20','','''number of linear iterations '''))
sfmdip.par('rect1',rsf.doc.rsfpar('int','1','','''dip smoothness on 1st axis '''))
sfmdip.par('rect2',rsf.doc.rsfpar('int','1','','''dip smoothness on 2nd axis '''))
sfmdip.par('p0',rsf.doc.rsfpar('float','0.','','''initial dip '''))
sfmdip.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfmdip.par('nj1',rsf.doc.rsfpar('int','1','','''antialiasing '''))
sfmdip.par('verb',rsf.doc.rsfpar('bool','n','','''verbosity flag '''))
sfmdip.par('pmin',rsf.doc.rsfpar('float','-FLT_MAX','','''minimum dip '''))
sfmdip.par('pmax',rsf.doc.rsfpar('float','+FLT_MAX','','''maximum dip '''))
sfmdip.par('eps',rsf.doc.rsfpar('float','0.0f','','''regularization '''))
sfmdip.par('mask',rsf.doc.rsfpar('string ',desc='''auxiliary input file name'''))
sfmdip.par('idip',rsf.doc.rsfpar('string ',desc='''initial in-line dip (auxiliary input file name)'''))
sfmdip.version('2.1-git Mdip2.c 7107 2011-04-10 02:04:14Z ivlad')
sfmdip.synopsis('''sfmdip < in.rsf > out.rsf mask=mask.rsf idip=idip0.rsf niter=5 liter=20 rect1=1 rect2=1 p0=0. order=1 nj1=1 verb=n pmin=-FLT_MAX pmax=+FLT_MAX eps=0.0f''','''''')
rsf.doc.progs['sfmdip']=sfmdip

sfodip2 = rsf.doc.rsfprog('sfodip2','user/pwd/Modip2.c','''2-D dip estimation by omnidirectional plane wave destruction. ''')
sfodip2.par('sin',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfodip2.par('cos',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfodip2.par('niter',rsf.doc.rsfpar('int','5','','''number of iterations '''))
sfodip2.par('liter',rsf.doc.rsfpar('int','50','','''number of linear iterations '''))
sfodip2.par('rect1',rsf.doc.rsfpar('int','1','','''dip smoothness on 1st axis '''))
sfodip2.par('rect2',rsf.doc.rsfpar('int','1','','''dip smoothness on 2nd axis '''))
sfodip2.par('a0',rsf.doc.rsfpar('float','0.','','''initial dip '''))
sfodip2.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfodip2.par('verb',rsf.doc.rsfpar('bool','y','','''verbosity flag '''))
sfodip2.par('sin',rsf.doc.rsfpar('string ',desc='''initial dip (sine) (auxiliary input file name)'''))
sfodip2.par('cos',rsf.doc.rsfpar('string ',desc='''initial dip (cosine) (auxiliary input file name)'''))
sfodip2.version('2.1-git')
sfodip2.synopsis('''sfodip2 < in.rsf > out.rsf sin=sn.rsf cos=cs.rsf niter=5 liter=50 rect1=1 rect2=1 a0=0. order=1 verb=y''','''''')
rsf.doc.progs['sfodip2']=sfodip2

sfofpwd = rsf.doc.rsfprog('sfofpwd','user/pwd/Mofpwd.c','''Objective function of dip estimation with PWD filters. ''')
sfofpwd.par('np',rsf.doc.rsfpar('int','100','','''number of dips '''))
sfofpwd.par('p0',rsf.doc.rsfpar('float','','','''dip origin '''))
sfofpwd.par('dp',rsf.doc.rsfpar('float','2*p0/(1.-np)','','''dip sampling '''))
sfofpwd.par('order',rsf.doc.rsfpar('int','1','[1,2,3]','''accuracy order '''))
sfofpwd.par('nj',rsf.doc.rsfpar('int','1','','''antialiasing '''))
sfofpwd.version('2.1-git')
sfofpwd.synopsis('''sfofpwd < in.rsf > of.rsf np=100 p0= dp=2*p0/(1.-np) order=1 nj=1''','''''')
rsf.doc.progs['sfofpwd']=sfofpwd

sfofpwd2 = rsf.doc.rsfprog('sfofpwd2','user/pwd/Mofpwd2.c','''Objective function of two dips estimation with PWD filters. ''')
sfofpwd2.par('np',rsf.doc.rsfpar('int','100','','''number of dips '''))
sfofpwd2.par('p0',rsf.doc.rsfpar('float','','','''first dip origin '''))
sfofpwd2.par('dp',rsf.doc.rsfpar('float','2*p0/(1.-np)','','''first dip sampling '''))
sfofpwd2.par('nq',rsf.doc.rsfpar('int','100','','''number of dips '''))
sfofpwd2.par('q0',rsf.doc.rsfpar('float','','','''second dip origin '''))
sfofpwd2.par('dq',rsf.doc.rsfpar('float','2*q0/(1.-nq)','','''second dip sampling '''))
sfofpwd2.par('order',rsf.doc.rsfpar('int','1','[1,2,3]','''accuracy order '''))
sfofpwd2.par('nj',rsf.doc.rsfpar('int','1','','''antialiasing '''))
sfofpwd2.version('2.1-git')
sfofpwd2.synopsis('''sfofpwd2 < in.rsf > of.rsf np=100 p0= dp=2*p0/(1.-np) nq=100 q0= dq=2*q0/(1.-nq) order=1 nj=1''','''''')
rsf.doc.progs['sfofpwd2']=sfofpwd2

sfopwd2 = rsf.doc.rsfprog('sfopwd2','user/pwd/Mopwd2.c','''2-D omnidirectional plane wave destruction. ''')
sfopwd2.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfopwd2.par('order',rsf.doc.rsfpar('int','1','','''accuracy '''))
sfopwd2.version('2.1-git')
sfopwd2.synopsis('''sfopwd2 < in.rsf dip=ang.rsf > out.rsf order=1''','''''')
rsf.doc.progs['sfopwd2']=sfopwd2

sfplanemis2 = rsf.doc.rsfprog('sfplanemis2','user/pwd/Mplanemis2.c','''Missing data interpolation in 2-D using plane-wave destruction. ''')
sfplanemis2.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfplanemis2.par('mask',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfplanemis2.par('niter',rsf.doc.rsfpar('int','100','','''number of iterations '''))
sfplanemis2.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfplanemis2.par('nj1',rsf.doc.rsfpar('int','1','','''antialiasing for first dip '''))
sfplanemis2.par('nj2',rsf.doc.rsfpar('int','1','','''antialiasing for second dip '''))
sfplanemis2.par('prec',rsf.doc.rsfpar('bool','n','','''if y, apply preconditioning '''))
sfplanemis2.par('verb',rsf.doc.rsfpar('bool','n','','''verbosity flag '''))
sfplanemis2.par('mask',rsf.doc.rsfpar('string ',desc='''auxiliary input file name'''))
sfplanemis2.version('2.1-git')
sfplanemis2.synopsis('''sfplanemis2 < in.rsf > out.rsf dip=dip.rsf mask=mask.rsf niter=100 order=1 nj1=1 nj2=1 prec=n verb=n''','''''')
rsf.doc.progs['sfplanemis2']=sfplanemis2

sfplanemis3 = rsf.doc.rsfprog('sfplanemis3','user/pwd/Mplanemis3.c','''Missing data interpolation in 3-D using plane-wave destruction. ''')
sfplanemis3.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfplanemis3.par('mask',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfplanemis3.par('niter',rsf.doc.rsfpar('int','100','','''number of iterations '''))
sfplanemis3.par('order',rsf.doc.rsfpar('int','1','[1,2,3]','''accuracy order '''))
sfplanemis3.par('nj1',rsf.doc.rsfpar('int','1','',''''''))
sfplanemis3.par('nj2',rsf.doc.rsfpar('int','1','','''antialiasing '''))
sfplanemis3.par('verb',rsf.doc.rsfpar('bool','n','','''verbosity flag '''))
sfplanemis3.par('seed',rsf.doc.rsfpar('int','time(NULL)','','''random seed '''))
sfplanemis3.par('var',rsf.doc.rsfpar('float','0.','','''noise variance '''))
sfplanemis3.par('mask',rsf.doc.rsfpar('string ',desc='''auxiliary input file name'''))
sfplanemis3.version('2.1-git')
sfplanemis3.synopsis('''sfplanemis3 < in.rsf > out.rsf dip=dip.rsf mask=mask.rsf niter=100 order=1 nj1=1 nj2=1 verb=n seed=time(NULL) var=0.''','''''')
rsf.doc.progs['sfplanemis3']=sfplanemis3

sfplanereg2 = rsf.doc.rsfprog('sfplanereg2','user/pwd/Mplanereg2.c','''Data regularization in 2-D using plane-wave destruction. ''')
sfplanereg2.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfplanereg2.par('interp',rsf.doc.rsfpar('int','2','','''interpolation length '''))
sfplanereg2.par('niter',rsf.doc.rsfpar('int','100','','''number of iterations '''))
sfplanereg2.par('order',rsf.doc.rsfpar('int','1','[1,2,3]','''accuracy order '''))
sfplanereg2.par('verb',rsf.doc.rsfpar('bool','n','','''verbosity flag '''))
sfplanereg2.par('eps',rsf.doc.rsfpar('float','0.01','','''regularization parameter '''))
sfplanereg2.par('head',rsf.doc.rsfpar('string ',desc=''''''))
sfplanereg2.version('2.1-git')
sfplanereg2.synopsis('''sfplanereg2 < in.rsf > out.rsf dip=dip.rsf interp=2 niter=100 order=1 verb=n eps=0.01 head=''','''''')
rsf.doc.progs['sfplanereg2']=sfplanereg2

sfplanereg3 = rsf.doc.rsfprog('sfplanereg3','user/pwd/Mplanereg3.c','''Data regularization in 3-D using plane-wave destruction. ''')
sfplanereg3.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfplanereg3.par('xkey',rsf.doc.rsfpar('int','','','''x key number '''))
sfplanereg3.par('ykey',rsf.doc.rsfpar('int','','','''y key number '''))
sfplanereg3.par('interp',rsf.doc.rsfpar('int','2','','''interpolation length '''))
sfplanereg3.par('niter',rsf.doc.rsfpar('int','100','','''number of iterations '''))
sfplanereg3.par('eps',rsf.doc.rsfpar('float','0.01','','''regularization parameter '''))
sfplanereg3.par('order',rsf.doc.rsfpar('int','1','[1,2,3]','''accuracy order '''))
sfplanereg3.par('nj1',rsf.doc.rsfpar('int','1','',''''''))
sfplanereg3.par('nj2',rsf.doc.rsfpar('int','1','','''antialiasing '''))
sfplanereg3.par('verb',rsf.doc.rsfpar('bool','n','','''verbosity flag '''))
sfplanereg3.par('head',rsf.doc.rsfpar('string ',desc=''''''))
sfplanereg3.version('2.1-git')
sfplanereg3.synopsis('''sfplanereg3 < in.rsf > out.rsf dip=dip.rsf xkey= ykey= interp=2 niter=100 eps=0.01 order=1 nj1=1 nj2=1 verb=n head=''','''''')
rsf.doc.progs['sfplanereg3']=sfplanereg3

sfplanesignoi = rsf.doc.rsfprog('sfplanesignoi','user/pwd/Mplanesignoi.c','''Signal and noise separation using plane-wave destruction filters.  ''')
sfplanesignoi.par('ndip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfplanesignoi.par('sdip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfplanesignoi.par('niter',rsf.doc.rsfpar('int','50','','''maximum number of iterations '''))
sfplanesignoi.par('eps',rsf.doc.rsfpar('float','1.','','''regularization parameter '''))
sfplanesignoi.par('order',rsf.doc.rsfpar('int','1','[1,2,3]','''accuracy order '''))
sfplanesignoi.par('nj1',rsf.doc.rsfpar('int','1','','''antialiasing for noise dip '''))
sfplanesignoi.par('nj2',rsf.doc.rsfpar('int','1','','''antialiasing for signal dip '''))
sfplanesignoi.par('verb',rsf.doc.rsfpar('bool','n','','''verbosity flag '''))
sfplanesignoi.version('2.1-git')
sfplanesignoi.synopsis('''sfplanesignoi < in.rsf ndip=ndip.rsf sdip=sdip.rsf > out.rsf niter=50 eps=1. order=1 nj1=1 nj2=1 verb=n''','''
If n3=1 in the output, outputs both signal and noise. Otherwise, only signal.
''')
rsf.doc.progs['sfplanesignoi']=sfplanesignoi

sfpmshape2 = rsf.doc.rsfprog('sfpmshape2','user/pwd/Mpmshape2.c','''Missing data interpolation in 2-D using plane-wave destruction and shaping regularization. ''')
sfpmshape2.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpmshape2.par('mask',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpmshape2.par('niter',rsf.doc.rsfpar('int','100','','''number of iterations '''))
sfpmshape2.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfpmshape2.par('rect1',rsf.doc.rsfpar('int','3','',''''''))
sfpmshape2.par('rect2',rsf.doc.rsfpar('int','3','','''smoothing radius '''))
sfpmshape2.par('mask',rsf.doc.rsfpar('string ',desc='''auxiliary input file name'''))
sfpmshape2.version('2.1-git')
sfpmshape2.synopsis('''sfpmshape2 < in.rsf > out.rsf dip=dip.rsf mask=mask.rsf niter=100 order=1 rect1=3 rect2=3''','''''')
rsf.doc.progs['sfpmshape2']=sfpmshape2

sfpredict = rsf.doc.rsfprog('sfpredict','user/pwd/Mpredict.c','''2-D plane-wave prediction. ''')
sfpredict.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpredict.par('adj',rsf.doc.rsfpar('bool','n','',''''''))
sfpredict.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfpredict.version('2.1-git Mtrismooth2.c 752 2004-08-22 21:57:40Z fomels')
sfpredict.synopsis('''sfpredict < in.rsf dip=dip.rsf > out.rsf adj=n order=1''','''''')
rsf.doc.progs['sfpredict']=sfpredict

sfpwcascade = rsf.doc.rsfprog('sfpwcascade','user/pwd/Mpwcascade.c','''Plane-wave smoothing by box cascade. ''')
sfpwcascade.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpwcascade.par('verb',rsf.doc.rsfpar('bool','n','','''verbosity '''))
sfpwcascade.par('eps',rsf.doc.rsfpar('float','0.01','','''regularization '''))
sfpwcascade.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfpwcascade.par('rect',rsf.doc.rsfpar('int','0','','''smoothing radius '''))
sfpwcascade.version('2.1-git')
sfpwcascade.synopsis('''sfpwcascade < inp.rsf dip=dip.rsf > out.rsf verb=n eps=0.01 order=1 rect=0''','''''')
rsf.doc.progs['sfpwcascade']=sfpwcascade

sfpwcoh = rsf.doc.rsfprog('sfpwcoh','user/pwd/Mpwcoh.c','''Coherency by plane-wave construction. ''')
sfpwcoh.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpwcoh.par('a2',rsf.doc.rsfpar('file   ',desc='''auxiliary output file name'''))
sfpwcoh.par('b2',rsf.doc.rsfpar('file   ',desc='''auxiliary output file name'''))
sfpwcoh.par('verb',rsf.doc.rsfpar('bool','n','',''''''))
sfpwcoh.par('eps',rsf.doc.rsfpar('float','0.01','','''regularization '''))
sfpwcoh.par('rect',rsf.doc.rsfpar('int','2','','''spread '''))
sfpwcoh.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfpwcoh.version('2.1-git Mflat.c 1131 2005-04-20 18:19:10Z fomels')
sfpwcoh.synopsis('''sfpwcoh < in.rsf > out.rsf dip=dip.rsf a2=a2.rsf b2=b2.rsf verb=n eps=0.01 rect=2 order=1''','''''')
rsf.doc.progs['sfpwcoh']=sfpwcoh

sfpwd = rsf.doc.rsfprog('sfpwd','user/pwd/Mpwd.c','''3-D plane wave destruction. ''')
sfpwd.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpwd.par('both',rsf.doc.rsfpar('bool','n','','''if y, compute both left and right predictions '''))
sfpwd.par('n4',rsf.doc.rsfpar('int','2','','''what to compute in 3-D. 0: in-line, 1: cross-line, 2: both '''))
sfpwd.par('order',rsf.doc.rsfpar('int','1','','''accuracy '''))
sfpwd.par('nj1',rsf.doc.rsfpar('int','1','','''in-line aliasing '''))
sfpwd.par('nj2',rsf.doc.rsfpar('int','1','','''cross-line aliasing '''))
sfpwd.version('2.1-git')
sfpwd.synopsis('''sfpwd < in.rsf dip=dip.rsf > out.rsf both=n n4=2 order=1 nj1=1 nj2=1''','''
February 2013 program of the month:
http://ahay.org/blog/2013/02/09/program-of-the-month-sfpwd/
''')
rsf.doc.progs['sfpwd']=sfpwd

sfpwd1 = rsf.doc.rsfprog('sfpwd1','user/pwd/Mpwd1.c','''One side of plane wave destruction. ''')
sfpwd1.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpwd1.par('left',rsf.doc.rsfpar('bool','y','','''if using left or right side of PWD '''))
sfpwd1.par('order',rsf.doc.rsfpar('int','1','','''accuracy '''))
sfpwd1.par('nj1',rsf.doc.rsfpar('int','1','','''in-line aliasing '''))
sfpwd1.par('nj2',rsf.doc.rsfpar('int','1','','''cross-line aliasing '''))
sfpwd1.version('2.1-git')
sfpwd1.synopsis('''sfpwd1 < in.rsf dip=dip.rsf > out.rsf left=y order=1 nj1=1 nj2=1''','''''')
rsf.doc.progs['sfpwd1']=sfpwd1

sfpwdchain = rsf.doc.rsfprog('sfpwdchain','user/pwd/Mpwdchain.c','''Nonstationary Prony by chain of PEFs ''')
sfpwdchain.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary output file name'''))
sfpwdchain.par('dipin',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpwdchain.par('nc',rsf.doc.rsfpar('int','1','','''number of components '''))
sfpwdchain.par('order',rsf.doc.rsfpar('int','1','','''PWD order '''))
sfpwdchain.par('verb',rsf.doc.rsfpar('bool','(bool) (1 == nt)','','''verbosity flag '''))
sfpwdchain.par('niter',rsf.doc.rsfpar('int','0','','''number of iterations '''))
sfpwdchain.par('liter',rsf.doc.rsfpar('int','50','','''number of linear iterations '''))
sfpwdchain.par('rect1',rsf.doc.rsfpar('int','1','',''''''))
sfpwdchain.par('rect2',rsf.doc.rsfpar('int','1','','''smoothing radius '''))
sfpwdchain.par('lambda',rsf.doc.rsfpar('float','1.0f','','''scaling '''))
sfpwdchain.par('dipin',rsf.doc.rsfpar('string ',desc='''auxiliary input file name'''))
sfpwdchain.version('2.1-git')
sfpwdchain.synopsis('''sfpwdchain < inp.rsf dip=dip.rsf > out.rsf dipin=dipin.rsf nc=1 order=1 verb=(bool) (1 == nt) niter=0 liter=50 rect1=1 rect2=1 lambda=1.0f''','''''')
rsf.doc.progs['sfpwdchain']=sfpwdchain

sfpwdchain1 = rsf.doc.rsfprog('sfpwdchain1','user/pwd/Mpwdchain1.c','''Chain of PWDs - linear operator ''')
sfpwdchain1.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpwdchain1.par('sig',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpwdchain1.par('adj',rsf.doc.rsfpar('bool','n','','''adjoint flag '''))
sfpwdchain1.version('2.1-git')
sfpwdchain1.synopsis('''sfpwdchain1 < inp.rsf dip=dip.rsf sig=sig.rsf > out.rsf adj=n''','''''')
rsf.doc.progs['sfpwdchain1']=sfpwdchain1

sfpwdchain2 = rsf.doc.rsfprog('sfpwdchain2','user/pwd/Mpwdchain2.c','''Chain of PWDs ''')
sfpwdchain2.par('sig',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpwdchain2.version('2.1-git')
sfpwdchain2.synopsis('''sfpwdchain2 < inp.rsf sig=sig.rsf > out.rsf''','''''')
rsf.doc.progs['sfpwdchain2']=sfpwdchain2

sfpwdix = rsf.doc.rsfprog('sfpwdix','user/pwd/Mpwdix.c','''Convert RMS to interval velocity using LS and plane-wave construction. ''')
sfpwdix.par('weight',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpwdix.par('slope',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpwdix.par('vrmsout',rsf.doc.rsfpar('file   ',desc='''auxiliary output file name'''))
sfpwdix.par('niter',rsf.doc.rsfpar('int','100','','''maximum number of iterations '''))
sfpwdix.par('ncycle',rsf.doc.rsfpar('int','10','','''number of cycles for anisotropic diffusion '''))
sfpwdix.par('rect1',rsf.doc.rsfpar('int','1','','''vertical smoothing radius '''))
sfpwdix.par('verb',rsf.doc.rsfpar('bool','n','','''verbosity flag '''))
sfpwdix.par('eps',rsf.doc.rsfpar('float','0.','','''regularization parameter '''))
sfpwdix.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfpwdix.par('vrmsout',rsf.doc.rsfpar('string ',desc='''optionally, output predicted vrms (auxiliary output file name)'''))
sfpwdix.version('2.1-git Mdix.c 803 2004-09-18 12:32:15Z fomels')
sfpwdix.synopsis('''sfpwdix < vrms.rsf > vint.rsf weight=weight.rsf slope=slope.rsf vrmsout=vout.rsf niter=100 ncycle=10 rect1=1 verb=n eps=0. order=1''','''''')
rsf.doc.progs['sfpwdix']=sfpwdix

sfpwdsigk = rsf.doc.rsfprog('sfpwdsigk','user/pwd/Mpwdsigk.c','''Signal component separation using plane-wave destruction. ''')
sfpwdsigk.par('dips',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpwdsigk.par('weight',rsf.doc.rsfpar('file   ',desc='''auxiliary output file name'''))
sfpwdsigk.par('niter',rsf.doc.rsfpar('int','50','','''maximum number of iterations '''))
sfpwdsigk.par('nliter',rsf.doc.rsfpar('int','1','','''number of reweighting iterations '''))
sfpwdsigk.par('eps',rsf.doc.rsfpar('float','0.','','''regularization parameter '''))
sfpwdsigk.par('verb',rsf.doc.rsfpar('bool','n','','''verbosity flag '''))
sfpwdsigk.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfpwdsigk.par('weight',rsf.doc.rsfpar('string ',desc='''auxiliary output file name'''))
sfpwdsigk.version('2.1-git')
sfpwdsigk.synopsis('''sfpwdsigk < in.rsf dips=dips.rsf > out.rsf weight=weight.rsf niter=50 nliter=1 eps=0. verb=n order=1''','''
The program works with 2-D data.
''')
rsf.doc.progs['sfpwdsigk']=sfpwdsigk

sfpwsmooth = rsf.doc.rsfprog('sfpwsmooth','user/pwd/Mpwsmooth.c','''2-D structure-enhancing filtering. ''')
sfpwsmooth.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpwsmooth.par('verb',rsf.doc.rsfpar('bool','n','','''verbosity flag '''))
sfpwsmooth.par('ns',rsf.doc.rsfpar('int','0','','''smoothing radius '''))
sfpwsmooth.par('adj',rsf.doc.rsfpar('bool','n','','''adjoint flag '''))
sfpwsmooth.par('eps',rsf.doc.rsfpar('float','0.01','','''regularization '''))
sfpwsmooth.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfpwsmooth.version('2.1-git')
sfpwsmooth.synopsis('''sfpwsmooth < in.rsf dip=dip.rsf > out.rsf verb=n ns=0 adj=n eps=0.01 order=1''','''''')
rsf.doc.progs['sfpwsmooth']=sfpwsmooth

sfpwsmooth2 = rsf.doc.rsfprog('sfpwsmooth2','user/pwd/Mpwsmooth2.c','''2-D structure-enhancing filtering: two slopes. ''')
sfpwsmooth2.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpwsmooth2.par('verb',rsf.doc.rsfpar('bool','n','','''verbosity flag '''))
sfpwsmooth2.par('ns',rsf.doc.rsfpar('int','0','','''smoothing radius '''))
sfpwsmooth2.par('adj',rsf.doc.rsfpar('bool','n','','''adjoint flag '''))
sfpwsmooth2.par('eps',rsf.doc.rsfpar('float','0.01','','''regularization '''))
sfpwsmooth2.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfpwsmooth2.version('2.1-git')
sfpwsmooth2.synopsis('''sfpwsmooth2 < in.rsf dip=dip.rsf > out.rsf verb=n ns=0 adj=n eps=0.01 order=1''','''''')
rsf.doc.progs['sfpwsmooth2']=sfpwsmooth2

sfpwpaint = rsf.doc.rsfprog('sfpwpaint','user/pwd/Mpwpaint.c','''Painting by plane-wave construction. ''')
sfpwpaint.par('seed',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpwpaint.par('verb',rsf.doc.rsfpar('bool','n','',''''''))
sfpwpaint.par('eps',rsf.doc.rsfpar('float','0.01','','''regularization '''))
sfpwpaint.par('i0',rsf.doc.rsfpar('int','0','','''reference trace '''))
sfpwpaint.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfpwpaint.par('seed',rsf.doc.rsfpar('string ',desc='''auxiliary input file name'''))
sfpwpaint.version('2.1-git Mflat.c 1131 2005-04-20 18:19:10Z fomels')
sfpwpaint.synopsis('''sfpwpaint < dip.rsf > out.rsf seed=seed.rsf verb=n eps=0.01 i0=0 order=1''','''''')
rsf.doc.progs['sfpwpaint']=sfpwpaint

sfpwpaint2 = rsf.doc.rsfprog('sfpwpaint2','user/pwd/Mpwpaint2.c','''3-D painting by plane-wave construction. ''')
sfpwpaint2.par('cost',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpwpaint2.par('seed',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpwpaint2.par('data',rsf.doc.rsfpar('bool','n','','''spray input data '''))
sfpwpaint2.par('verb',rsf.doc.rsfpar('bool','n','',''''''))
sfpwpaint2.par('eps',rsf.doc.rsfpar('float','0.01','','''regularization '''))
sfpwpaint2.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfpwpaint2.par('seed',rsf.doc.rsfpar('string ',desc='''auxiliary input file name'''))
sfpwpaint2.version('2.1-git')
sfpwpaint2.synopsis('''sfpwpaint2 < dip.rsf > out.rsf cost=cost.rsf seed=seed.rsf data=n verb=n eps=0.01 order=1''','''''')
rsf.doc.progs['sfpwpaint2']=sfpwpaint2

sfpwspray2 = rsf.doc.rsfprog('sfpwspray2','user/pwd/Mpwspray2.c','''Plane-wave spray in 3-D. ''')
sfpwspray2.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpwspray2.par('verb',rsf.doc.rsfpar('bool','n','','''verbosity '''))
sfpwspray2.par('eps',rsf.doc.rsfpar('float','0.01','','''regularization '''))
sfpwspray2.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfpwspray2.par('ns2',rsf.doc.rsfpar('int','','',''''''))
sfpwspray2.par('ns3',rsf.doc.rsfpar('int','','','''spray radius '''))
sfpwspray2.version('2.1-git')
sfpwspray2.synopsis('''sfpwspray2 < inp.rsf dip=dip.rsf > out.rsf verb=n eps=0.01 order=1 ns2= ns3=''','''''')
rsf.doc.progs['sfpwspray2']=sfpwspray2

sfpwspray3 = rsf.doc.rsfprog('sfpwspray3','user/pwd/Mpwspray3.c','''Plane-wave spray in 3-D. ''')
sfpwspray3.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpwspray3.par('verb',rsf.doc.rsfpar('bool','n','','''verbosity '''))
sfpwspray3.par('eps',rsf.doc.rsfpar('float','0.01','','''regularization '''))
sfpwspray3.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfpwspray3.par('ns2',rsf.doc.rsfpar('int','','',''''''))
sfpwspray3.par('ns3',rsf.doc.rsfpar('int','','','''spray radius '''))
sfpwspray3.version('2.1-git')
sfpwspray3.synopsis('''sfpwspray3 < inp.rsf dip=dip.rsf > out.rsf verb=n eps=0.01 order=1 ns2= ns3=''','''''')
rsf.doc.progs['sfpwspray3']=sfpwspray3

sfpwdsmooth2 = rsf.doc.rsfprog('sfpwdsmooth2','user/pwd/Mpwdsmooth2.c','''2-D smoothing by triangle plane-wave construction shaping. ''')
sfpwdsmooth2.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpwdsmooth2.par('rect1',rsf.doc.rsfpar('int','3','',''''''))
sfpwdsmooth2.par('rect2',rsf.doc.rsfpar('int','3','','''smoothing radius '''))
sfpwdsmooth2.par('adj',rsf.doc.rsfpar('bool','n','','''adjoint flag '''))
sfpwdsmooth2.par('verb',rsf.doc.rsfpar('bool','n','','''verbosity flag '''))
sfpwdsmooth2.par('eps',rsf.doc.rsfpar('float','0.01','','''regularization '''))
sfpwdsmooth2.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfpwdsmooth2.version('2.1-git')
sfpwdsmooth2.synopsis('''sfpwdsmooth2 < in.rsf dip=dip.rsf > out.rsf rect1=3 rect2=3 adj=n verb=n eps=0.01 order=1''','''''')
rsf.doc.progs['sfpwdsmooth2']=sfpwdsmooth2

sfpwpaint3 = rsf.doc.rsfprog('sfpwpaint3','user/pwd/Mpwpaint3.c','''3-D painting by plane-wave construction. ''')
sfpwpaint3.par('seed',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpwpaint3.par('cost',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpwpaint3.par('verb',rsf.doc.rsfpar('bool','n','',''''''))
sfpwpaint3.par('eps',rsf.doc.rsfpar('float','0.01','','''regularization '''))
sfpwpaint3.par('ref2',rsf.doc.rsfpar('int','0','',''''''))
sfpwpaint3.par('ref3',rsf.doc.rsfpar('int','0','','''reference trace '''))
sfpwpaint3.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfpwpaint3.version('2.1-git Mflat.c 743 2004-08-16 20:41:00Z fomels')
sfpwpaint3.synopsis('''sfpwpaint3 < dip.rsf > out.rsf seed=seed.rsf cost=cost.rsf verb=n eps=0.01 ref2=0 ref3=0 order=1''','''''')
rsf.doc.progs['sfpwpaint3']=sfpwpaint3

sfpwspray = rsf.doc.rsfprog('sfpwspray','user/pwd/Mpwspray.c','''Plane-wave spray. ''')
sfpwspray.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpwspray.par('verb',rsf.doc.rsfpar('bool','n','','''verbosity '''))
sfpwspray.par('eps',rsf.doc.rsfpar('float','0.01','','''regularization '''))
sfpwspray.par('ns',rsf.doc.rsfpar('int','','','''spray radius '''))
sfpwspray.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfpwspray.par('rect',rsf.doc.rsfpar('int','2','','''radius for predictive coherence (reduce=coherence) '''))
sfpwspray.par('reduce',rsf.doc.rsfpar('string ',desc='''reduction method (none,stack,median,triangle,gaussian,predict,coherence) '''))
sfpwspray.version('2.1-git')
sfpwspray.synopsis('''sfpwspray < inp.rsf dip=dip.rsf > out.rsf verb=n eps=0.01 ns= order=1 rect=2 reduce=''','''''')
rsf.doc.progs['sfpwspray']=sfpwspray

sfpwstack = rsf.doc.rsfprog('sfpwstack','user/pwd/Mpwstack.c','''Recursive stacking by plane-wave construction. ''')
sfpwstack.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfpwstack.par('verb',rsf.doc.rsfpar('bool','n','',''''''))
sfpwstack.par('eps',rsf.doc.rsfpar('float','0.01','','''regularization '''))
sfpwstack.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfpwstack.par('mode',rsf.doc.rsfpar('int','1','','''1: predict backward, 2: predict forward then backward '''))
sfpwstack.version('2.1-git')
sfpwstack.synopsis('''sfpwstack < inp.rsf dip=dip.rsf > out.rsf verb=n eps=0.01 order=1 mode=1''','''''')
rsf.doc.progs['sfpwstack']=sfpwstack

sfseisigk = rsf.doc.rsfprog('sfseisigk','user/pwd/Mseisigk.c','''Signal component separation using seislet transforms. ''')
sfseisigk.par('dips',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfseisigk.par('weight',rsf.doc.rsfpar('file   ',desc='''auxiliary output file name'''))
sfseisigk.par('niter',rsf.doc.rsfpar('int','50','','''maximum number of iterations '''))
sfseisigk.par('nliter',rsf.doc.rsfpar('int','1','','''number of reweighting iterations '''))
sfseisigk.par('eps',rsf.doc.rsfpar('float','0.','','''regularization parameter '''))
sfseisigk.par('eps0',rsf.doc.rsfpar('float','0.01','','''regularization for seislet '''))
sfseisigk.par('verb',rsf.doc.rsfpar('bool','n','','''verbosity flag '''))
sfseisigk.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfseisigk.par('weight',rsf.doc.rsfpar('string ',desc='''auxiliary output file name'''))
sfseisigk.par('type',rsf.doc.rsfpar('string ',desc='''wavelet type (haar,linear) '''))
sfseisigk.version('2.1-git')
sfseisigk.synopsis('''sfseisigk < in.rsf dips=dips.rsf > out.rsf weight=weight.rsf niter=50 nliter=1 eps=0. eps0=0.01 verb=n order=1 type=''','''
The program works with 2-D data. The second dimension should be a power of 2.
''')
rsf.doc.progs['sfseisigk']=sfseisigk

sfseislet = rsf.doc.rsfprog('sfseislet','user/pwd/Mseislet.c','''Seislet transform ''')
sfseislet.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfseislet.par('inv',rsf.doc.rsfpar('bool','n','','''if y, do inverse transform '''))
sfseislet.par('adj',rsf.doc.rsfpar('bool','n','','''if y, do adjoint transform '''))
sfseislet.par('eps',rsf.doc.rsfpar('float','0.01','','''regularization '''))
sfseislet.par('unit',rsf.doc.rsfpar('bool','n','','''if y, use unitary scaling '''))
sfseislet.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfseislet.par('verb',rsf.doc.rsfpar('bool','n','','''verbosity flag '''))
sfseislet.par('type',rsf.doc.rsfpar('string ',desc='''[haar,linear,biorthogonal] wavelet type, the default is linear  '''))
sfseislet.version('2.1-git')
sfseislet.synopsis('''sfseislet < in.rsf > out.rsf dip=dip.rsf inv=n adj=n eps=0.01 unit=n order=1 verb=n type=''','''
April 2017 program of the month:
http://ahay.org/blog/2017/04/19/program-of-the-month-sfseislet/
''')
rsf.doc.progs['sfseislet']=sfseislet

sfshapesigk = rsf.doc.rsfprog('sfshapesigk','user/pwd/Mshapesigk.c','''Signal component separation using plane-wave shaping. ''')
sfshapesigk.par('dips',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfshapesigk.par('niter',rsf.doc.rsfpar('int','50','','''maximum number of iterations '''))
sfshapesigk.par('eps',rsf.doc.rsfpar('float','1.','','''regularization parameter '''))
sfshapesigk.par('verb',rsf.doc.rsfpar('bool','n','','''verbosity flag '''))
sfshapesigk.par('rect1',rsf.doc.rsfpar('int','1','','''vertical smoothing radius '''))
sfshapesigk.par('rect2',rsf.doc.rsfpar('int','1','','''lateral smoothing radius '''))
sfshapesigk.version('2.1-git')
sfshapesigk.synopsis('''sfshapesigk < in.rsf dips=dips.rsf > out.rsf niter=50 eps=1. verb=n rect1=1 rect2=1''','''
The program works with 2-D data.
''')
rsf.doc.progs['sfshapesigk']=sfshapesigk

sfshplanemis2 = rsf.doc.rsfprog('sfshplanemis2','user/pwd/Mshplanemis2.c','''Missing data interpolation in 2-D using plane-wave shaping regularization. ''')
sfshplanemis2.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfshplanemis2.par('mask',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfshplanemis2.par('niter',rsf.doc.rsfpar('int','100','','''number of iterations '''))
sfshplanemis2.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfshplanemis2.par('ns',rsf.doc.rsfpar('int','1','','''smoothing radius '''))
sfshplanemis2.par('eps',rsf.doc.rsfpar('float','0.01','','''regularization '''))
sfshplanemis2.par('mask',rsf.doc.rsfpar('string ',desc='''auxiliary input file name'''))
sfshplanemis2.version('2.1-git')
sfshplanemis2.synopsis('''sfshplanemis2 < in.rsf > out.rsf dip=dip.rsf mask=mask.rsf niter=100 order=1 ns=1 eps=0.01''','''''')
rsf.doc.progs['sfshplanemis2']=sfshplanemis2

sfshplanemis3 = rsf.doc.rsfprog('sfshplanemis3','user/pwd/Mshplanemis3.c','''Missing data interpolation in 3-D using plane-wave shaping regularization. ''')
sfshplanemis3.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfshplanemis3.par('mask',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfshplanemis3.par('niter',rsf.doc.rsfpar('int','100','','''number of iterations '''))
sfshplanemis3.par('order1',rsf.doc.rsfpar('int','1','',''''''))
sfshplanemis3.par('order2',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfshplanemis3.par('ns1',rsf.doc.rsfpar('int','1','',''''''))
sfshplanemis3.par('ns2',rsf.doc.rsfpar('int','1','','''smoothing radius '''))
sfshplanemis3.par('eps',rsf.doc.rsfpar('float','0.01','','''regularization '''))
sfshplanemis3.par('mask',rsf.doc.rsfpar('string ',desc='''auxiliary input file name'''))
sfshplanemis3.version('2.1-git')
sfshplanemis3.synopsis('''sfshplanemis3 < in.rsf > out.rsf dip=dip.rsf mask=mask.rsf niter=100 order1=1 order2=1 ns1=1 ns2=1 eps=0.01''','''''')
rsf.doc.progs['sfshplanemis3']=sfshplanemis3

sftimeshift = rsf.doc.rsfprog('sftimeshift','user/pwd/Mtimeshift.c','''Apply variable time shifts using plane-wave construction. ''')
sftimeshift.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sftimeshift.par('eps',rsf.doc.rsfpar('float','0.01','','''regularization '''))
sftimeshift.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sftimeshift.version('2.1-git')
sftimeshift.synopsis('''sftimeshift < inp.rsf > out.rsf dip=dip.rsf eps=0.01 order=1''','''''')
rsf.doc.progs['sftimeshift']=sftimeshift

sftrismooth2 = rsf.doc.rsfprog('sftrismooth2','user/pwd/Mtrismooth2.c','''2-D smoothing by triangle directional shaping. ''')
sftrismooth2.par('dip',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sftrismooth2.par('rect1',rsf.doc.rsfpar('int','3','',''''''))
sftrismooth2.par('rect2',rsf.doc.rsfpar('int','3','','''smoothing radius '''))
sftrismooth2.par('adj',rsf.doc.rsfpar('bool','n','',''''''))
sftrismooth2.version('2.1-git')
sftrismooth2.synopsis('''sftrismooth2 < in.rsf dip=dip.rsf > out.rsf rect1=3 rect2=3 adj=n''','''''')
rsf.doc.progs['sftrismooth2']=sftrismooth2

sftwodip2 = rsf.doc.rsfprog('sftwodip2','user/pwd/Mtwodip2.c','''2-D two dip estimation by plane wave destruction.''')
sftwodip2.par('dip1',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sftwodip2.par('dip2',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sftwodip2.par('mask',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sftwodip2.par('niter',rsf.doc.rsfpar('int','5','','''number of iterations '''))
sftwodip2.par('eps',rsf.doc.rsfpar('float','1','','''vertical smoothness '''))
sftwodip2.par('lam',rsf.doc.rsfpar('float','1','','''horizontal smoothness '''))
sftwodip2.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sftwodip2.par('nj1',rsf.doc.rsfpar('int','1','','''antialiasing for first dip '''))
sftwodip2.par('nj2',rsf.doc.rsfpar('int','1','','''antialiasing for second dip '''))
sftwodip2.par('verb',rsf.doc.rsfpar('bool','n','','''verbosity flag '''))
sftwodip2.par('sign',rsf.doc.rsfpar('bool','n','','''if y, keep dip sign constant '''))
sftwodip2.par('gauss',rsf.doc.rsfpar('bool','n','','''if y, use exact Gaussian for smoothing '''))
sftwodip2.par('both',rsf.doc.rsfpar('bool','y','','''if y, estimate both dips '''))
sftwodip2.par('p0',rsf.doc.rsfpar('float','1.','','''initial first dip '''))
sftwodip2.par('q0',rsf.doc.rsfpar('float','0.','','''initial second dip '''))
sftwodip2.par('dip1',rsf.doc.rsfpar('string ',desc='''auxiliary input file name'''))
sftwodip2.par('dip2',rsf.doc.rsfpar('string ',desc='''auxiliary input file name'''))
sftwodip2.par('mask',rsf.doc.rsfpar('string ',desc='''auxiliary input file name'''))
sftwodip2.version('2.1-git')
sftwodip2.synopsis('''sftwodip2 < in.rsf > out.rsf dip1=dip1.rsf dip2=dip2.rsf mask=mask.rsf niter=5 eps=1 lam=1 order=1 nj1=1 nj2=1 verb=n sign=n gauss=n both=y p0=1. q0=0. < data.rsf > dip.rsf''','''''')
rsf.doc.progs['sftwodip2']=sftwodip2

sfdistpaint = rsf.doc.rsfprog('sfdistpaint','user/pwd/Mdistpaint.c','''Geologic distance painting by plane-wave construction. ''')
sfdistpaint.par('seed',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfdistpaint.par('flt',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfdistpaint.par('verb',rsf.doc.rsfpar('bool','n','',''''''))
sfdistpaint.par('eps',rsf.doc.rsfpar('float','0.01','','''regularization '''))
sfdistpaint.par('i0',rsf.doc.rsfpar('int','0','','''reference trace '''))
sfdistpaint.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfdistpaint.par('faultscale',rsf.doc.rsfpar('float','100.','','''Fault attribute scaling factor (0.0 ~ factor) '''))
sfdistpaint.par('seed',rsf.doc.rsfpar('string ',desc='''auxiliary input file name'''))
sfdistpaint.par('flt',rsf.doc.rsfpar('string ',desc='''auxiliary input file name'''))
sfdistpaint.version('2.1-git')
sfdistpaint.synopsis('''sfdistpaint < dip.rsf > out.rsf seed=seed.rsf flt=flt.rsf verb=n eps=0.01 i0=0 order=1 faultscale=100.''','''''')
rsf.doc.progs['sfdistpaint']=sfdistpaint

sfdistpaint3D = rsf.doc.rsfprog('sfdistpaint3D','user/pwd/Mdistpaint3D.c','''3-D painting by plane-wave construction. ''')
sfdistpaint3D.par('seed',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfdistpaint3D.par('flt',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfdistpaint3D.par('cost',rsf.doc.rsfpar('file   ',desc='''auxiliary input file name'''))
sfdistpaint3D.par('verb',rsf.doc.rsfpar('bool','n','',''''''))
sfdistpaint3D.par('eps',rsf.doc.rsfpar('float','0.01','','''regularization '''))
sfdistpaint3D.par('ref2',rsf.doc.rsfpar('int','0','',''''''))
sfdistpaint3D.par('ref3',rsf.doc.rsfpar('int','0','','''reference trace '''))
sfdistpaint3D.par('order',rsf.doc.rsfpar('int','1','','''accuracy order '''))
sfdistpaint3D.par('faultscale',rsf.doc.rsfpar('float','100.','','''Fault attribute scaling factor (0.0 ~ factor) '''))
sfdistpaint3D.version('2.1-git')
sfdistpaint3D.synopsis('''sfdistpaint3D < dip.rsf > out.rsf seed=seed.rsf flt=flt.rsf cost=cost.rsf verb=n eps=0.01 ref2=0 ref3=0 order=1 faultscale=100.''','''''')
rsf.doc.progs['sfdistpaint3D']=sfdistpaint3D

