[sfmpircvrtm]
Cat:    RSF/user/jsun
Desc:   2-D Low-rank One-step Least Pre-stack Reverse-Time-Migration in the complex domain (both img and data are complex valued)
DocCmd: sfmpircvrtm | cat
Port:   input rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   left rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   leftb rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   output rsf w  -  		auxiliary output file name (containing unspecified data)
Port:   rec2 rsf w  -  		auxiliary output file name (containing unspecified data)
Port:   right rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   rightb rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   src rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   tmpwf rsf w  -  		auxiliary output file name (containing unspecified data)
Port:   vel rsf r  -  		auxiliary input file name (containing unspecified data)
Param:  adj enum-bool  -  y 		migration
Param:  bot int  -  40 		
Param:  depth int  -   -  		muting source depth -> receiver depth according reciprocity
LDesc:  (defaults to: gpz)
Param:  gpl int  -   -  		
Param:  gpz int  -   -  		
Param:  illum enum-bool  -  n 		if n, no source illumination applied 
Param:  lft int  -  40 		
Param:  mute enum-bool  -  n 		muting in the receiver gather
Param:  pad1 int  -  1 		padding factor on the first axis 
Param:  rcvbgn int  -  0 		
Param:  rcvend int  -  -1 		
Param:  rcvint int  -  1 		
Param:  rectx int  -  1 		
Param:  rectz int  -  1 		
Param:  repeat int  -  0 		abc parameters 
Param:  rht int  -  40 		
Param:  rmig enum-bool  -  n 		receiver domain migration
Param:  roll enum-bool  -  n 		if n, receiver is independent of source location and gpl=nx
Param:  sht0 int  -   -  		actual shot origin on grid
LDesc:  (defaults to: shtbgn)
Param:  shtbgn int  -   -  		
Param:  shtend int  -   -  		
Param:  shtint int  -   -  		
Param:  snapinter int  -  1 		snap interval 
Param:  spx int-list  -   -  		 [num_of_shots]
Param:  spz int  -   -  		
Param:  srctrunc float  -  0.4 		
Param:  stack enum-bool  -  y 		if y, outputs stacked image
Param:  top int  -  40 		
Param:  verb enum-bool  -  n 		verbosity
Param:  vref float  -  1500 		
Param:  wantrecord enum-bool  -  y 		if n, using record data generated by this program 
Param:  wantwf enum-bool  -  n 		output forward and backward wavefield
Param:  wd int  -  5 		

