[sfsglfdrtm2]
Cat:    RSF/user/fangg
Desc:   None
DocCmd: sfsglfdrtm2 | cat
Port:   stdin  rsf r req 	RSF standard input (containing Fsrc data)
Port:   stdout rsf w req 	RSF standard output (containing Fimg1 data)
Port:   Gx rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   Gz rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   bden rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   bvel rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   fden rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   fvel rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   img2 rsf w  -  		auxiliary output file name (containing unspecified data)
Port:   rec rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   sxx rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   sxz rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   szx rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   szz rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   tmpbwf rsf w  -  		auxiliary output file name (containing unspecified data)
Port:   tmpwf rsf w  -  		auxiliary output file name (containing unspecified data)
Param:  decay enum-bool  -   -  		Flag of decay boundary condtion: 1 = use ; 0 = not use 
LDesc:  (defaults to: DECAY_FLAG)
Param:  decaybegin int  -   -  		Begin time of using decay boundary condition 
LDesc:  (defaults to: DECAY_BEGIN)
Param:  freesurface enum-bool  -  n 		free surface
Param:  gdep float  -   -  		recorder depth on grid
Param:  ginter int  -  1 		geophone interval
Param:  gp int  -   -  		recorder depth on index
Param:  pmld0 int  -   -  		PML parameter 
LDesc:  (defaults to: PMLD0)
Param:  pmlsize int  -   -  		size of PML layer 
LDesc:  (defaults to: PMLOUT)
Param:  slx float  -   -  		source location x 
Param:  slz float  -   -  		source location z 
Param:  snapinter int  -  10 		snap interval 
Param:  spx int  -   -  		source location x (index)
Param:  spz int  -   -  		source location z (index)
Param:  srcdecay enum-bool  -   -  		source decay
LDesc:  (defaults to: SRCDECAY)
Param:  srcrange int  -   -  		source decay range
LDesc:  (defaults to: SRCRANGE)
Param:  srctrunc float  -   -  		trunc source after srctrunc time (s)
LDesc:  (defaults to: SRCTRUNC)
Param:  verb enum-bool  -  n 		verbosity
Param:  wantrecord enum-bool  -  y 		if n, using record data generated by this program 
Param:  wantwf enum-bool  -  n 		output forward and backward wavefield

