[sfvtihti2ort]
Cat:    RSF/user/zone
Desc:   Combining VTI and HTI parameters to orthorhombic according to Schoenberg & Sayer (1995)
DocCmd: sfvtihti2ort | cat
Port:   stdin  rsf r req 	RSF standard input (containing c33 data)
Port:   stdout rsf w req 	RSF standard output (containing c11o data)
Port:   c11h rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   c11v rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   c12h rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   c12o rsf w  -  		auxiliary output file name (containing unspecified data)
Port:   c12v rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   c13h rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   c13o rsf w  -  		auxiliary output file name (containing unspecified data)
Port:   c13v rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   c16o rsf w  -  		auxiliary output file name (containing unspecified data)
Port:   c22o rsf w  -  		auxiliary output file name (containing unspecified data)
Port:   c23o rsf w  -  		auxiliary output file name (containing unspecified data)
Port:   c26o rsf w  -  		auxiliary output file name (containing unspecified data)
Port:   c33o rsf w  -  		auxiliary output file name (containing unspecified data)
Port:   c36o rsf w  -  		auxiliary output file name (containing unspecified data)
Port:   c44o rsf w  -  		auxiliary output file name (containing unspecified data)
Port:   c45o rsf w  -  		auxiliary output file name (containing unspecified data)
Port:   c55 rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   c55h rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   c55o rsf w  -  		auxiliary output file name (containing unspecified data)
Port:   c66o rsf w  -  		auxiliary output file name (containing unspecified data)
Port:   c66v rsf r  -  		auxiliary input file name (containing unspecified data)
Port:   phi rsf r  -  		auxiliary input file name (containing unspecified data)
Param:  rotate enum-bool  -  n 		Doing azimuthal rotation (y-> mono, n-> ortho)

