.TH sfai2refl 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sfai2refl \- Convert acoustic impedance to reflectivity. 
.SH SYNOPSIS
.B sfai2refl < ai.rsf > mod.rsf
.SH COMMENTS

August 2013 program of the month:
http://www.ahay.org/blog/2013/08/02/program-of-the-month-sfai2refl/

.SH USED IN
.TP
.I cwp/geo2006TimeShiftImagingCondition/flat
.TP
.I gallery/marmousi/model
.TP
.I gallery/overthrust/model
.TP
.I gallery/segsalt/model
.TP
.I gallery/sigsbee/model
.TP
.I gallery/twohalf/model
.TP
.I geo384w/hw5/lsmig
.TP
.I geo384w/hw6/sigsbee
.TP
.I rsf/rsf/wedge
.TP
.I rsf/school2015/modmig
.TP
.I rsf/su/rsfwellrf
.TP
.I rsf/tutorials/cg
.TP
.I rsf/tutorials/inv
.TP
.I rsf/tutorials/tuning
.TP
.I rsf/tutorials/wedge
.TP
.I rsf/tutorials/well-tie
.TP
.I sep/fat/migration
.TP
.I sep/geostat/dix
.TP
.I tccs/attr/attr
.TP
.I tccs/fraclapl/marmq
.TP
.I tccs/gmresq/bpgas
.TP
.I tccs/gmresq/exploding
.TP
.I tccs/synth/ordexample20hz
.TP
.I tccs/synth/small-khuff
.TP
.I xjtu/test/marmousi
.TP
1 more examples listed in:
.TP
/home/raptor/rsfsrc/share/doc/madagascar/html/sfai2refl.html
.SH SOURCE
.I system/seismic/Mai2refl.c
.SH VERSION
2.1-git
