.TH sfbackdire 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sfbackdire \- Background directivity(Dip). 
.SH SYNOPSIS
.B sfbackdire < Zz.rsf > Zo.rsf verb=0
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B verb
.B =0
.R  [y/n]
.SH USED IN
.TP
.I tccs/strat/three-d
.SH SOURCE
.I user/parvaneh/Mbackdire.c
.SH VERSION
2.1-git
