.TH sfcabs 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sfcabs \- Absolute value complex data. 
.SH SYNOPSIS
.B sfcabs < fin.rsf > fout.rsf
.SH USED IN
.TP
.I tccs/dbortho/hyper
.TP
.I tccs/deblend/fairfield-initmfnew
.TP
.I tccs/deblend/linear
.TP
.I tccs/deblend/synthcomplex
.TP
.I tccs/deblend/synthhyper
.TP
.I tccs/dsd/conflict
.TP
.I tccs/dsd/demo
.TP
.I tccs/dsd/demo2
.TP
.I tccs/dsd/demo3.1perc
.TP
.I tccs/eseis/demo2
.TP
.I tccs/eseis/demo4
.TP
.I tccs/intshape/fsyn
.TP
.I tccs/intshape/sean
.TP
.I tccs/svmf/fairfield
.TP
.I tccs/svmf/test
.TP
.I tccs/svmf/testnoise
.TP
.I tccs/synwav/pp
.SH SOURCE
.I user/chenyk/Mcabs.c
.SH VERSION
2.1-git
