.TH sfcmplx 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sfcmplx \- Create a complex dataset from its real and imaginary parts.
.SH SYNOPSIS
.B sfcmplx < real.rsf > cmplx.rsf real.rsf imag.rsf
.SH COMMENTS
There has to be only two input files specified and no additional parameters.

.SH USED IN
.TP
.I cwp/geo2008NumericWEMVAoperators/flatWEMVA
.TP
.I cwp/geo2008NumericWEMVAoperators/saltWEMVA
.TP
.I data/teapotdome/geom
.TP
.I data/teapotdome/tahscscale
.TP
.I gallery/sigsbee/lrostep
.TP
.I gee/lsq/vesuvio
.TP
.I geo384h/hw4/invint
.TP
.I geo384s/hw2/land3d
.TP
.I geo384w/hw2/eikonal
.TP
.I geo384w/hw5/hyper
.TP
.I rsf/bash/plot
.TP
.I rsf/challenge/rain
.TP
.I rsf/rsf/sfgraph
.TP
.I rsf/school2012/plot
.TP
.I rsf/school2017/gravity
.TP
.I rsf/su/rsflab11
.TP
.I rsf/tutorials/attr
.TP
.I rsf/tutorials/cs
.TP
.I rsf/tutorials/hilbert
.TP
.I rsf/tutorials/petro1
.TP
.I rsf/tutorials/well-tie
.TP
.I sep/bspl/sei3d
.TP
.I sep/fmeiko/tri
.TP
.I sep/fmsec/cvel
.TP
.I sep/precon/cube
.TP
65 more examples listed in:
.TP
/home/raptor/rsfsrc/share/doc/madagascar/html/sfcmplx.html
.SH SOURCE
.I system/main/cmplx.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfcmplx
.SH VERSION
2.1-git
