.TH sfcmatrix 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sfcmatrix \- multiply, for complex Matrix 
.SH SYNOPSIS
.B sfcmatrix < inA.rsf B=inB.rsf > outC.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B B
.B =
.R  	auxiliary input file name
.SH USED IN
.TP
.I tccs/onestep/fio1d
.SH SOURCE
.I user/jsun/Mcmatrix.c
.SH VERSION
2.1-git
