.TH sfcostaper 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sfcostaper \- Cosine taper around the borders (N-D). 
.SH SYNOPSIS
.B sfcostaper < in.rsf > out.rsf nw#=0
.SH COMMENTS

April 2014 program of the month:
http://ahay.org/blog/2014/04/02/program-of-the-month-sfcostaper/

.SH PARAMETERS
.PD 0
.TP
.I int    
.B nw#
.B =0
.R  	tapering on #-th axis
.SH USED IN
.TP
.I data/nankai/data
.TP
.I gallery/french/lowrank
.TP
.I gallery/gradient/fakirmig
.TP
.I gallery/gradient/lowrank
.TP
.I gallery/gradient/model
.TP
.I gallery/gradient/oway
.TP
.I gallery/marmousi/model
.TP
.I gallery/overthrust/model
.TP
.I gallery/sigsbee/ffd
.TP
.I gallery/sigsbee/lowrank
.TP
.I gallery/sigsbee/lrostep
.TP
.I gallery/sigsbee/model
.TP
.I gallery/sigsbee/oway
.TP
.I gallery/twohalf/model
.TP
.I gallery/vofz/gazdag
.TP
.I gallery/vofz/kirch
.TP
.I gallery/vofz/lowrank
.TP
.I gallery/vofz/model
.TP
.I gallery/vofz/oway
.TP
.I gallery/vofz/stolt
.TP
.I gallery/vofz/vc
.TP
.I gee/ajt/igrad1
.TP
.I gee/hlx/helderiv
.TP
.I gee/hlx/helocut
.TP
.I geo384h/hw3/compress
.TP
21 more examples listed in:
.TP
/home/raptor/rsfsrc/share/doc/madagascar/html/sfcostaper.html
.SH SOURCE
.I system/generic/Mcostaper.c
.SH VERSION
2.1-git
