.TH sfcp 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sfcp \- Copy or move a dataset.
.SH SYNOPSIS
.B sfcp < in.rsf > out.rsf in.rsf out.rsf
.SH COMMENTS
sfcp - copy, sfmv - move.
Mimics standard Unix commands.

.SH USED IN
.TP
.I gallery/hessvti/model
.TP
.I gee/mda/mad
.TP
.I rsf/school/modeling
.TP
.I rsf/school/trig
.TP
.I rsf/tutorials/images
.TP
.I tccs/dbortho/hyper
.TP
.I tccs/deblend/fairfield-initmfnew
.TP
.I tccs/deblend/linear
.TP
.I tccs/deblend/synthcomplex
.TP
.I tccs/deblend/synthhyper
.TP
.I tccs/dsd/demo2
.TP
.I tccs/dsd/demo3.1perc
.TP
.I tccs/emdpf/fxdecon
.TP
.I tccs/emdpf/linear
.TP
.I tccs/eseis/demo2
.TP
.I tccs/eseis/demo4
.TP
.I tccs/eseis/sparse
.TP
.I tccs/fwiseislet/blend
.TP
.I tccs/fwiseislet/encoding-spar
.TP
.I tccs/fwiseislet/encoding
.TP
.I tccs/fwiseislet/noise-spar
.TP
.I tccs/fwiseislet/noise
.TP
.I tccs/fwiseislet/timedomain
.TP
.I tccs/fwiseislet/wavelet
.TP
.I tccs/intshape/fsyn
.TP
11 more examples listed in:
.TP
/home/raptor/rsfsrc/share/doc/madagascar/html/sfcp.html
.SH SOURCE
.I system/main/cp.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfcp
.SH VERSION
2.1-git
