.TH sfdifference 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sfdifference \- Difference profile of two data 
.SH SYNOPSIS
.B sfdifference < in.rsf > out.rsf subtracter=sub.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B subtracter
.B =
.R  	auxiliary input file name
.SH USED IN
.TP
.I swag/eikds/marm2
.TP
.I swag/eikds/smvel
.TP
.I swag/waveds/fdmod
.TP
.I swag/waveds/fdmodnoSS
.TP
.I swag/waveds/svmod
.SH SOURCE
.I user/yliu/Mdifference.c
.SH VERSION
2.1-git
