.TH sfdwt 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sfdwt \- 1-D digital wavelet transform 
.SH SYNOPSIS
.B sfdwt < in.rsf > out.rsf inv=n adj=n unit=n type=
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	if y, do adjoint transform
.TP
.I bool   
.B inv
.B =n
.R  [y/n]	if y, do inverse transform
.TP
.I string 
.B type
.B =
.R  	[haar,linear,biorthogonal] wavelet type, the default is linear
.TP
.I bool   
.B unit
.B =n
.R  [y/n]	if y, use unitary scaling
.SH USED IN
.TP
.I rsf/rsf/gui
.TP
.I tccs/eseis/demo2
.TP
.I tccs/eseis/demo4
.TP
.I tccs/eseis/field
.TP
.I tccs/eseis/nonseis
.TP
.I tccs/eseis/sparse
.TP
.I tccs/fwiseislet/wavelet
.TP
.I tccs/oc3/french
.TP
.I tccs/oc3/frenchint
.TP
.I tccs/seislet/gath
.TP
.I tccs/seislet/lena
.TP
.I tccs/seislet/seis
.SH SOURCE
.I system/generic/Mdwt.c
.SH VERSION
2.1-git
