.TH sffinstack 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sffinstack \- DMO and stack by finite-difference offset continuation. 
.SH SYNOPSIS
.B sffinstack < cmp.rsf > stk.rsf
.SH USED IN
.TP
.I geo384w/hw3/synth
.TP
.I tccs/diffr/fault
.TP
.I tccs/nmodeblend/bei
.TP
.I tccs/nmodeblend/synth
.TP
.I tccs/pi/bei
.TP
.I tccs/vscan/stack
.SH SOURCE
.I system/seismic/Mfinstack.c
.SH VERSION
2.1-git
