.TH sfhelicon 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sfhelicon \- Multidimensional convolution and deconvolution by helix transform. 
.SH SYNOPSIS
.B sfhelicon < in.rsf filt=filt.rsf > out.rsf n= adj=n div=n lag=
.SH COMMENTS

May 2014 program of the month:
http://ahay.org/blog/2014/05/13/program-of-the-month-sfhelicon/

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	if y, do adjoint operation
.TP
.I bool   
.B div
.B =n
.R  [y/n]	if y, do inverse operation (deconvolution)
.TP
.I file   
.B filt
.B =
.R  	auxiliary input file name
.TP
.I string 
.B lag
.B =
.R  	file with filter lags
.TP
.I ints   
.B n
.B =
.R  	 [dim]
.SH USED IN
.TP
.I cup/rna2d/real
.TP
.I cup/rna2d/shot
.TP
.I cup/rna2d/simple
.TP
.I gee/hlx/helderiv
.TP
.I gee/hlx/helgal
.TP
.I gee/hlx/helicon
.TP
.I gee/hlx/helocut
.TP
.I gee/hlx/mam
.TP
.I gee/mda/elita
.TP
.I gee/mda/geostat
.TP
.I gee/mda/mad
.TP
.I gee/mda/morgan
.TP
.I gee/mda/pefex
.TP
.I gee/prc/sep95
.TP
.I geo384h/hw2/helix
.TP
.I geo384h/hw4/invint
.TP
.I geo384h/hw5/pattern
.TP
.I geo384h/hw5/seabeam
.TP
.I jlu/txsopf/curvedmodel
.TP
.I jlu/txyapf/curve
.TP
.I jlu/txyapf/sigmoid
.TP
.I rsf/tutorials/smoothing
.TP
.I sep/bspl/plane3
.TP
.I sep/burg/gtens
.TP
.I sep/burg/helix
.TP
13 more examples listed in:
.TP
/home/raptor/rsfsrc/share/doc/madagascar/html/sfhelicon.html
.SH SOURCE
.I user/gee/Mhelicon.c
.SH VERSION
2.1-git
