.TH sfheadersort 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sfheadersort \- Sort a dataset according to a header key. 
.SH SYNOPSIS
.B sfheadersort < in.rsf > out.rsf head=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B head
.B =
.R  	header file
.SH USED IN
.TP
.I bei/ft1/autocor
.TP
.I data/seam-phase1-2d/cvs
.TP
.I geo384s/hw2/land3d
.TP
.I geo384s/hw3/nmo3d
.TP
.I geo384s/hw6/gazdag
.TP
.I rsf/rsf/plot
.TP
.I rsf/rsf/sfwiggle
.TP
.I rsf/su/rsflab14
.TP
.I rsf/tutorials/colormaps
.TP
.I sep/pefmult/haskell
.TP
.I sep/pefmult/mobil
.TP
.I sep/pefmult/syn
.SH SOURCE
.I system/main/headersort.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfheadersort
.SH VERSION
2.1-git
