.TH sfhole 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sfhole \- Cut an elliptic hole in data (for interpolation tests).
.SH SYNOPSIS
.B sfhole < in.rsf > out.rsf maskout=mask.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B maskout
.B =
.R  	auxiliary output file name
.SH USED IN
.TP
.I gee/lal/multiscale
.TP
.I gee/mda/elita
.TP
.I gee/mda/geostat
.TP
.I gee/mda/hole
.TP
.I gee/mda/morgan
.TP
.I sep/pwd/hole
.SH SOURCE
.I user/gee/Mhole.c
.SH VERSION
2.1-git
