.TH sfintegral1 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sfintegral1 \- integration 
.SH SYNOPSIS
.B sfintegral1 < Fin.rsf > Fout.rsf rule=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B rule
.B =
.R  	t, s : quadrature rules
.SH USED IN
.TP
.I swag/tau/hess
.TP
.I swag/tau/iso
.TP
.I swag/tau/lens
.TP
.I swag/tau/linear
.TP
.I swag/tau/marm
.TP
.I swag/tau/vertical
.SH SOURCE
.I user/xuxin/Mintegral1.c
.SH VERSION
2.1-git
