.TH sfinttest1 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sfinttest1 \- Interpolation from a regular grid in 1-D. 
.SH SYNOPSIS
.B sfinttest1 < in.rsf > out.rsf coord=crd.rsf nw= same=y kai=4.0 interp=
.SH COMMENTS

January 2014 program of the month:
http://ahay.org/blog/2014/01/09/program-of-the-month-sfinttest1/

.SH PARAMETERS
.PD 0
.TP
.I file   
.B coord
.B =
.R  	auxiliary input file name
.TP
.I string 
.B interp
.B =
.R  	interpolation (lagrange,cubic,kaiser,lanczos,cosine,welch,spline,mom)
.TP
.I float  
.B kai
.B =4.0
.R  	Kaiser window parameter
.TP
.I int    
.B nw
.B =
.R  	interpolator size
.TP
.I bool   
.B same
.B =y
.R  [y/n]	same or different coordinates for each trace
.SH USED IN
.TP
.I data/alaska/line31-81-m8r
.TP
.I geo384s/hw2/groundroll
.TP
.I rsf/tutorials/cs
.TP
.I rsf/tutorials/hilbert
.TP
.I rsf/tutorials/well-tie
.TP
.I sep/bspl/chirp
.TP
.I sep/forwd/chirp
.TP
.I tccs/pi/barrolka
.TP
.I tccs/t2dweak/alaska
.TP
.I tccs/timelapse/timelapse
.TP
.I tccs/uncert/beivc
.SH SOURCE
.I system/generic/Minttest1.c
.SH VERSION
2.1-git
