.TH sfjpg2byte 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sfjpg2byte \- Convert JPEG image to byte RSF. 
.SH SYNOPSIS
.B sfjpg2byte > out.rsf < file.jpeg 
.SH USED IN
.TP
.I rsf/tutorials/images
.TP
.I rsf/tutorials/talitrus
.TP
.I tccs/vc3/fracs
.SH SOURCE
.I user/fomels/_jpg2byte.c
.SH VERSION
2.1-git
