.TH sflinefit 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sflinefit \- Fit a line to a set of points in 2-D.
.SH SYNOPSIS
.B sflinefit < in.rsf > out.rsf pattern=pattern.rsf
.SH PARAMETERS
.PD 0
.TP
.I string 
.B pattern
.B =
.R  	auxiliary input file name
.SH USED IN
.TP
.I tccs/attr/vecta
.TP
.I tccs/ltft/vecta
.SH SOURCE
.I system/generic/Mlinefit.c
.SH VERSION
2.1-git
