.TH sflpef 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sflpef \- Find PEF on aliased traces. 
.SH SYNOPSIS
.B sflpef < dat.rsf > pef.rsf a= center= gap= jump=2 lag=
.SH PARAMETERS
.PD 0
.TP
.I ints   
.B a
.B =
.R  	 [dim]
.TP
.I ints   
.B center
.B =
.R  	 [dim]
.TP
.I ints   
.B gap
.B =
.R  	 [dim]
.TP
.I int    
.B jump
.B =2
.R  
.TP
.I string 
.B lag
.B =
.R  	output file for filter lags
.SH USED IN
.TP
.I gee/lal/lace
.TP
.I jlu/txyapf/curve
.TP
.I jlu/txyapf/sigmoid
.TP
.I tccs/apefint/alias
.TP
.I tccs/apefint/ray
.SH SOURCE
.I user/gee/Mlpef.c
.SH VERSION
2.1-git
