.TH sflpf 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sflpf \- Local prediction filter (n-dimensional). 
.SH SYNOPSIS
.B sflpf < dat.rsf match=mat.rsf > flt.rsf pred=pre.rsf niter=100 verb=y pef= lag=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B lag
.B =
.R  	file with PEF lags (optional)
.TP
.I file   
.B match
.B =
.R  	auxiliary input file name
.TP
.I int    
.B niter
.B =100
.R  	number of iterations
.TP
.I string 
.B pef
.B =
.R  	signal PEF file (optional)
.TP
.I string 
.B pred
.B =
.R  	auxiliary output file name
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity flag
.SH USED IN
.TP
.I geo384h/hw5/pattern
.TP
.I jlu/riesz/linefit
.TP
.I sep/stack/velinv
.TP
.I tccs/amf/misfitexample
.TP
.I tccs/lpf/lpf
.TP
.I tccs/lpf/plut
.TP
.I tccs/lpf/ray
.TP
.I tccs/lpf/regr
.TP
.I tccs/lpf/simon
.TP
.I tccs/nar/trace
.TP
.I tccs/pi/bei
.TP
.I tccs/pi/simple-model
.SH SOURCE
.I user/fomels/Mlpf.c
.SH VERSION
2.1-git
