.TH sfmedian 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sfmedian \- Compute median on the first axis. 
.SH SYNOPSIS
.B sfmedian < in.rsf > out.rsf
.SH USED IN
.TP
.I rsf/tutorials/semblance
.TP
.I tccs/orthogroll/field
.TP
.I tccs/sobel/pari
.TP
.I tccs/sobel/penobscot
.SH SOURCE
.I user/fomels/Mmedian.c
.SH VERSION
2.1-git
