.TH sfmysnr 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sfmysnr \- print out signal-to-noise ratio in decibel (dB)
.SH SYNOPSIS
.B sfmysnr < in.rsf ref=ref.rsf > out.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B ref
.B =
.R  	auxiliary input file name
.SH USED IN
.TP
.I xjtu/mcaseislet/interp
.SH SOURCE
.I user/pyang/Mmysnr.c
.SH VERSION
2.1-git
