.TH sfpow 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sfpow \- Apply power gain. 
.SH SYNOPSIS
.B sfpow < in.rsf > out.rsf tpow= pow#=(0,0,...)
.SH COMMENTS

March 2013 program of the month:
http://www.ahay.org/blog/2013/03/10/program-of-the-month-sfpow/

.SH PARAMETERS
.PD 0
.TP
.I float  
.B pow#
.B =(0,0,...)
.R  	power on #-th axis
.TP
.I float  
.B tpow
.B =
.R  
.SH USED IN
.TP
.I bei/dpmv/matt
.TP
.I bei/dwnc/vofz
.TP
.I bei/fld/yc
.TP
.I bei/ft1/brad
.TP
.I bei/krch/sep73
.TP
.I bei/sg/denmark
.TP
.I bei/vela/stretch
.TP
.I bei/wvs/head
.TP
.I data/alaska/line31-81-m8r
.TP
.I data/nankai/data
.TP
.I data/nankai/shots
.TP
.I data/seam-phase1-2d/cvs
.TP
.I data/segsalt/data
.TP
.I data/viking/decon
.TP
.I data/viking/fetch
.TP
.I data/viking/firstlook
.TP
.I gallery/bptti/model
.TP
.I gallery/model94/model
.TP
.I gallery/statics94/model
.TP
.I gee/lmn/sep73
.TP
.I gee/lsq/antoine
.TP
.I gee/mda/pefex
.TP
.I gee/noiz/softclip
.TP
.I gee/pch/mideast
.TP
.I gee/pch/steep
.TP
49 more examples listed in:
.TP
/home/raptor/rsfsrc/share/doc/madagascar/html/sfpow.html
.SH SOURCE
.I system/generic/Mpow.c
.SH VERSION
2.1-git
