.TH sfsplinefilter 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sfsplinefilter \- Convert data to B-spline coefficients. 
.SH SYNOPSIS
.B sfsplinefilter < in.rsf > out.rsf nw=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B nw
.B =
.R  	filter size
.SH USED IN
.TP
.I sep/bspl/chirp
.TP
.I sep/forwd/chirp
.SH SOURCE
.I system/generic/Msplinefilter.c
.SH VERSION
2.1-git
