.TH sfspectra2 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sfspectra2 \- Frequency spectra in 2-D. 
.SH SYNOPSIS
.B sfspectra2 < in.rsf > out.rsf all=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B all
.B =n
.R  [y/n]	if y, compute average spectrum for all traces
.SH USED IN
.TP
.I data/freeusp/land
.TP
.I geo384h/hw5/seabeam
.TP
.I jlu/vdseislet/usp
.TP
.I rsf/school/data
.TP
.I rsf/school2017/seismic
.TP
.I tccs/seislet/lena
.SH SOURCE
.I system/generic/Mspectra2.c
.SH VERSION
2.1-git
