.TH sfst 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sfst \- S transform 
.SH SYNOPSIS
.B sfst < in.rsf > out.rsf inv=n flo= fhi=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B fhi
.B =
.R  	High frequency in band, default is Nyquist
.TP
.I float  
.B flo
.B =
.R  	Low frequency in band, default is 0
.TP
.I bool   
.B inv
.B =n
.R  [y/n]	if y, do inverse transform
.SH USED IN
.TP
.I tccs/ltft/timefreq
.TP
.I tccs/synwav/gch1
.TP
.I tccs/synwav/lowf
.TP
.I tccs/synwav/pp
.TP
.I tccs/timefreq/lowf
.TP
.I tccs/timefreq/syn
.SH SOURCE
.I user/yliu/Mst.c
.SH VERSION
2.1-git
