.TH sfthr 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sfthr \- Threshold float/complex inputs given a constant/varying threshold level.
.SH SYNOPSIS
.B sfthr < in.rsf > out.rsf fthr=fthr.rsf thr= mode=
.SH COMMENTS

Methods available:
- soft
- hard
- non-negative Garrote (nng)

Written by: Gilles Hennenfent & Colin Russell, UBC
Created: February 2006

.SH PARAMETERS
.PD 0
.TP
.I string 
.B fthr
.B =
.R  	varying threshold level (positive number) (auxiliary input file name)
.TP
.I string 
.B mode
.B =
.R  	'soft', 'hard', 'nng' (default: soft)
.TP
.I float  
.B thr
.B =
.R  	threshold level (positive number)
.SH USED IN
.TP
.I geo384h/hw3/compress
.TP
.I rsf/scons/rsfpy
.TP
.I rsf/tutorials/cs
.TP
.I slim/slimUserManual/sffdct
.TP
.I slim/slimUserManual/sfthr
.TP
.I tccs/aii/heidrun
.TP
.I tccs/dsrtomo/marm
.SH SOURCE
.I user/slim/Mthr.c
.SH VERSION
2.1-git
