.TH sfvam 1  "APRIL 2019" Madagascar "Madagascar Manuals"
.SH NAME
sfvam \- Create a layered model. 
.SH SYNOPSIS
.B sfvam > vfile.rsf nz= nx= dz= dx=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dx
.B =
.R  	distance sampling
.TP
.I float  
.B dz
.B =
.R  	depth sampling
.TP
.I int    
.B nx
.B =
.R  	distance grid
.TP
.I int    
.B nz
.B =
.R  	depth grid
.SH USED IN
.TP
.I trip/hpcss/test1
.TP
.I trip/hpcss/test2
.TP
.I trip/hpcss/test3
.TP
.I trip/hpcss/test4
.TP
.I trip/hpcss/test5
.SH SOURCE
.I user/hpcss/Mvam.c
.SH VERSION
2.1-git
